package com.xiaopengwei.springboot.mybatis.mapper;

import com.xiaopengwei.springboot.mybatis.entity.StudentEO;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface StudentEOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Apr 12 14:55:46 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Apr 12 14:55:46 CST 2019
     */
    int insert(StudentEO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Apr 12 14:55:46 CST 2019
     */
    int insertSelective(StudentEO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Apr 12 14:55:46 CST 2019
     */
    StudentEO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Apr 12 14:55:46 CST 2019
     */
    int updateByPrimaryKeySelective(StudentEO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbg.generated Fri Apr 12 14:55:46 CST 2019
     */
    int updateByPrimaryKey(StudentEO record);

    List<StudentEO> selectAll();
}